coverage:
  range: 60..80
  round: down
  precision: 2
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
  status:
    project:
      default:
        target: auto
        threshold: 5%
        branches:
          - main
    patch:
      default:
        target: auto
        threshold: 5%
        branches:
          - main
