coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: 90
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 5%

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
