coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 5%
        branches:
          - main
    patch:
      default:
        target: auto
        threshold: 5%
        branches:
          - main
